### ISSUE TITLE
Google Drive package fails to update.

### ISSUE THREAD

**Issue by dtheurer-control4** [mkevenaar/chocolatey-packages#138]
This warning has been there for a long time but, it hasn't been fixed.  Several package users are experiencing based on the comments on the package: https://community.chocolatey.org/packages/googledrive

Installing googledrive...
2022-07-08T16:20:44.750ZI [42476:NonCelloThread] i18n.cc:311:InitializeI18n I18n initialized with en
WARNING: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'googledrive' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\Users\myuser\AppData\Local\Temp\chocolatey\googledrive\59.0.3.0\GoogleDriveSetup.exe" --silent --desktop_shortcut ] was not successful. Exit code was '1638'. Exit code indicates the following: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'googledrive' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The upgrade of googledrive was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\googledrive\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by itsolutek** [comment]
I experience this too. As I explained on the package page, it seems that Google Drive updates itself and the version showing on Chocolatey doesn't match the installed one.
On my choco, it says I have the 62.0.1.0 installed, being out of date because the latest is 62.0.2.0. However, the version installed is 62.0.2.0.
Google Drive installer will pop up saying "This version of Google Drive is already installed"

![Google Drive Update Issue - version discrepency](https://user-images.githubusercontent.com/58011947/186852549-a44640cb-89f7-4a45-87e8-538daa095e09.png)
