### ISSUE TITLE
(sqlitebrowser.install) lacks of Start Menu shortcut

### ISSUE THREAD

**Issue by T1mL3arn** [mkevenaar/chocolatey-packages#28]
## Expected Behavior

Start Menu shortcut can be found in Start Menu after installation.

## Current Behavior

There is no shortcut to [_DB browser for SQLite_](https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/sqlitebrowser.install) in startup menu. It is needed to locate the program on disk and create shortcut manually and place it to Start Menu.

## Possible Solution

[Create shortcut](https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyShortcut) with installation script.

**Comment by chrisjlocke** [comment]
Just a nod that (technically) it will require two shortcuts (well, maybe four).  There are two .exe's provided in the package - normal DB4S, and a sqlCipher version.  I assume a shortcut would be placed on the desktop as well as the start menu?
Some have suggested just a shortcut to the SQLCipher version could be used, but this does (sometimes) tend to have a different version of SQLite, depending on the timeframe, and the SQLCipher development cycle.

**Comment by chrisjlocke** [comment]
Just another nod that it would be handy to chocolatise (?!) the nightly versions of DB4S.  Maybe not the /actual/ nightlies, as that could be a maintenance nightmare, and I don't know how long it takes for a package to be vetted and made available, but maybe weekly at the least.  The development of DB4S can be in spit and spurts, while the actual 'final release' of a build can be quite lengthy (especially due to translations into various languages).  Getting people to install a nightly version via Chocolatey could be useful and easy.
